### ISSUE TITLE
Error when trying to open folder in quick tag 

### ISSUE THREAD

**Issue by codingvivi** [Marekkon5/onetagger#230]
When trying to open a specific folder on the external SSD my music is on I get the error "WebSocket closed!" followed by the error "[object Event]". Onetagger then tries to load the contents of the folder into infinity.

 This effectively makes me soft locked, since OneTagger is stuck on loading and neither allows me to leave the "Quick Tag" page, nor does it respond to any attempts to change the file path. Closing OneTagger and opening up again and then changing the path in the settings menu before it has the chance to try to reload the broken path makes me unstuck again.

The folder is on an external SSD. It is a big folder (51.81 GB) and contains audio files, album art Traktor created, .asd files Ableton Live created, a .tsi mapping file and a m3u file. There are no subdirectories. I tried copying all of the music without the other files into a different folder and got the same error. Other folders on the same SSD work fine. I am on macOS Monterrey 12.5.1

**Comment by Marekkon5** [comment]
Hello, it's probably some sort of permission denied thing since macOS. Could you please send the log? (reopen 1T > settings > open data folder > onetagger.log). Thank you

**Comment by codingvivi** [comment]
This is the log from when I opened OneTagger and recreated the issue. The folder loaded on startup (`/Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging`) worked fine, the folder `/Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection` is the one that softlocks OneTagger

```
Starting OneTagger v1.6.0 Commit: 429b0e82 OS: macos


2023-06-06 18:03:15 [INFO] onetagger::ui: Starting server on http://127.0.0.1:36913 ws://127.0.0.1:36912
2023-06-06 18:04:15 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging/01 You Are the One (feat. Sheilah Cuffy).m4a Missing artist tag
2023-06-06 18:04:15 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging/Alois - Intro.wav Missing artist tag
2023-06-06 18:04:16 [WARN] onetagger::ui: Error loading album art: Missing album art! File: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging/02 Love You Better (Extended Mix).m4a
2023-06-06 18:04:16 [WARN] onetagger::ui: Error loading album art: Missing album art! File: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging/B1. DJ Sneak - Show Me The Way.mp3
2023-06-06 18:04:16 [WARN] onetagger::ui: Error loading album art: Missing album art! File: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging/Men i trust - Tailwhip (Lewii Edit) - Club_Soundcloud master.wav
2023-06-06 18:04:16 [WARN] onetagger::ui: Error loading album art: Missing album art! File: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Tagging/01 4Real (Crackazat Remix) [feat. BB James].m4a
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /Lancaster. - STHRN GRL.wav Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /acloudysky - Exile.wav Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /Subformat -  Don't Look Behind.mp3 Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /KELIS BOUNCE ACAPELLA 1.mp3 Missing title tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /Kubix - Vapour.mp3 Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /Kaskade ft. Ilsey - Disarm You (Ryos vs. Slywalker Remix) Extended.mp3.mp3 Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /Noize - Got this for you.wav Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /03 Learn to Fly (feat. Jordan Rakei).m4a Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger::quicktag: Error loading file: /Volumes/Work SSD 2/Music/Electronic Music Sorted/Collection /07 Outrun 9000.m4a Missing artist tag
2023-06-06 18:04:29 [ERROR] onetagger_shared: PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/riff-1.0.1/src/lib.rs:186:57
2023-06-06 18:04:29 [ERROR] onetagger_shared: LOCATION: File: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/riff-1.0.1/src/lib.rs, Line: 186
2023-06-06 18:04:42 [INFO] onetagger: 
```

**Comment by Marekkon5** [comment]
Hello, I've added a fix in the latest commit, so it shouldn't crash anymore. However one of your WAV files has a bad RIFF chunk (should be skipped now). You can get the binary from the Actions tab. Feel free to comment / reopen if you have more issues. Thanks

**Comment by mtsbh** [comment]
Same here. Two files processing and after the second one I receive websocket closed and I can't play anything anymore. OS - Arch Linux

**Comment by Marekkon5** [comment]
@mtsbh Hello, could you please provide the log? It's in `~/.config/onetagger/onetagger.log`. Thank you

**Comment by mtsbh** [comment]
Sure. The most of it are errors for missing tags, but the logs ends with:
```
2023-07-28 05:16:21 [ERROR] onetagger_shared: PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: Error { input: [], code: Eof }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pacmog-0.4.1/src/lib.rs:266:83
2023-07-28 05:16:21 [ERROR] onetagger_shared: LOCATION: File: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pacmog-0.4.1/src/lib.rs, Line: 266
2023-07-28 05:16:21 [ERROR] onetagger_shared: PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: Error { input: [], code: Eof }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pacmog-0.4.1/src/lib.rs:266:83
2023-07-28 05:16:21 [ERROR] onetagger_shared: LOCATION: File: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pacmog-0.4.1/src/lib.rs, Line: 266
2023-07-28 05:16:55 [ERROR] onetagger_shared: PANIC: panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/onetagger-player/src/lib.rs:112:24
2023-07-28 05:16:55 [ERROR] onetagger_shared: LOCATION: File: crates/onetagger-player/src/lib.rs, Line: 112
```

**Comment by Marekkon5** [comment]
@mtsbh It seems like some of your AIFF files are corrupted / have invalid chunks / truncated. 1T shouldn't panic anymore from the latest commit (you can get the binary from the Actions tab), but it won't be able to play those files. Feel free to comment / reopen if you have more issues.
